spring.application.name=myApp

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/workshop?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Debug log
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

# Secret key (login)
jwt.secret=HEaPU8v2FrZVJtJOmkVhMAmzXtj2DXsWELtULYrx5uH
jwt.expiration-days=120

# Secret key (reset password)
reset.secret=1Rj0krFe6Wmw2Kn3TbwqW0vDeVB6CedZhkrZD05VtCl
reset.expiration-minutes=30

#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wingkin0713@gmail.com
spring.mail.password=idnhppltyhamrudt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.main.allow-circular-references=true

app.frontend.url=http://localhost:5173

# 🔥 允許你的 Netlify + 本地前端訪問後端（必加！）
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:5174,https://erb-team-project-ngrok.netlify.app
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true